[launcher]
author = SMT
description = Splunk Health Check — consolidated health checks from Monitoring Console, Health Assistant Add-on, and SMT best practices.
version = 1.0.0

[package]
id = splunk_health_check
check_for_updates = 0

[ui]
is_visible = 1
label = Health Check

[app]
build = 1

[id]
group = SMT
name = splunk_health_check
version = 1.0.0
